### ISSUE TITLE
Corgi Engine

### ISSUE THREAD

**Issue by reunono** [Liweimin0512/EntitasTutorial#1]
Hello,

I'm the creator of the Corgi Engine. 
Your repo contains Corgi Engine files, and I'm afraid you can't redistribute it like that, I'll have to ask you to remove it from Github immediately, or make this repo private, or it'll be taken down.

Thank you,
Renaud.

**Comment by Liweimin0512** [comment]
i'm sorry for that ,i like Corgi Engine very much ,its very coooool, Because of carelessness，and now i remove it in this repertory。and i will  support yours all the time。im sorry again。forgive my English is poor
